### ISSUE TITLE
You have merge conflicts

### ISSUE THREAD

**Issue by FearThe1337** [megoesrawr/LWCEntityLocking#1]
Just to let you know, you have code here with merge conflicts :)

https://github.com/megoesrawr/LWCEntityLocking/blob/master/LWC/com/griefcraft/listeners/LWCPlayerListener.java#L173
https://github.com/megoesrawr/LWCEntityLocking/blob/master/LWC/com/griefcraft/listeners/LWCPlayerListener.java#L202
https://github.com/megoesrawr/LWCEntityLocking/blob/master/LWC/com/griefcraft/listeners/LWCPlayerListener.java#L245

**Comment by megoesrawr** [comment]
Thanks.
