### ISSUE TITLE
Upstream merge?

### ISSUE THREAD

**Issue by mibby** [megoesrawr/LWCEntityLocking#11]
Would it be possible to merge upstream source commits into your fork, or is it so far removed that newer commits can't be merged without problems? For example, I noticed cinfo on a lock does not display the name of the player with the UUID, just the UUID.

There are also some newer hopper optimizations here I noticed.
https://github.com/Minebench/LWC/commits/master

**Comment by megoesrawr** [comment]
Maybe.... ill look into it.

**Comment by totemo** [comment]
+1 for a pull request.
