### ISSUE TITLE
Order of entity locking

### ISSUE THREAD

**Issue by minifisch** [megoesrawr/LWCEntityLocking#12]
Check first if the entity has locking enabled in the config file from lwc and _then_ check the permission node. Should improve performance a bit.

**Comment by megoesrawr** [comment]
Umm.... maybe... i think LWC already does that.

**Comment by minifisch** [comment]
LWC does. But not your implementation of entity locking. Put PEX on your server and then enable debug mode. You can clearly see, that you get a permission check for that specific node if you do not have that entity registered in the LWC (EntityLWC) settings. This means, that if you right click on any entity (Cows for example) there will be a permission check.
