### ISSUE TITLE
Update to 1.11

### ISSUE THREAD

**Issue by Platinteufel** [megoesrawr/LWCEntityLocking#13]
Hey @megoesrawr,

is it possible to push an EntityLWC version for CB 1.11 in the next weeks? Thank you! ;)
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-1-11-released.193887/
https://www.spigotmc.org/threads/bukkit-1-11-api-draft.193437/

**Comment by megoesrawr** [comment]
Coming soon.... (Like in 10 mins)

**Comment by Platinteufel** [comment]
Thanks, that was fast. :+1:
Short question: Is it possible to lock shulker boxes?

**Comment by megoesrawr** [comment]
If you add them i think so, i havent tested it yet

**Comment by Platinteufel** [comment]
Spigot updated the packaged SQLite version to 3.15, so that there are errors like this:

[10:01:37 INFO]: [LWC] Connecting to SQLite
[10:01:37 ERROR]: Error occurred while enabling LWC v1.7.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/sqlite/NativeDB

Do you know if LWC packages it's own SQLite?

**Comment by Platinteufel** [comment]
And if so, is it possible for you to update the driver?

**Comment by megoesrawr** [comment]
I updated the driver. Check spigot for it.
