### ISSUE TITLE
/lock does not work

### ISSUE THREAD

**Issue by Mario359** [megoesrawr/LWCEntityLocking#15]
I use Spigot 1.11 with the last version of LWC
I deactivated the option to secure automatically  objects
Players have to make /lock to secure their objects
But when we make /lock and right click to secure, it spends it nothing and no errors
(Sorry I'm not English)

**Comment by megoesrawr** [comment]
It still works for me....

**Comment by Mario359** [comment]
Sorry !
The bug came from another plugin

LWC works fine
