### ISSUE TITLE
Double noticed when clicking Iron Door

### ISSUE THREAD

**Issue by jessefjxm** [megoesrawr/LWCEntityLocking#17]
Came up with an strange bug that when clicking iron door with either by hand or a door in hand, it'll give double response in chat. Clicking with blocks or other items (haven't test for all items) just works fine.
If you enabled "opening iron door when clicked", it'll be opened and immediate closed. I tried LWC with new config, but the problem still exist.

Server: spigoit 1.10.2
LWC: 1.7.6
No error or warning in the console.

**Comment by sigmaroot** [comment]
Yes confirmed.

The DoorsModule is fired twice when a iron door is clicked.
All other doors work as expected.

**Comment by sigmaroot** [comment]
Additional information: Every right click is fired twice. Simple protected signs are also fired twice.

**Comment by megoesrawr** [comment]
This is a Spigot issue. No idea why though...

**Comment by megoesrawr** [comment]
I CAN fix it BUT it will be limited to 1.9+

**Comment by sigmaroot** [comment]
Thanks. Works! Left click is firing the open/close mechanic too, but that's no problem.

**Comment by jessefjxm** [comment]
It's probably the problem of 'left-arm'. In spigot 1.9+ look like all click will fire the event twice, one with main hand, one with another.
