### ISSUE TITLE
Can't unlock entity with left click

### ISSUE THREAD

**Issue by shone-zmaj** [megoesrawr/LWCEntityLocking#2]
When you try to brake your item frame and paintings you can't until you unlock them by doing /unlock and then right click instead of left even if it says punch your protection to remove the lock and if you punch it it says "[LWC] you have a pending action but another plugin cancelled it!"

**Comment by megoesrawr** [comment]
"When you try to brake your item frame and paintings you can't until you unlock them by doing /unlock" is suppose to happen and im trying to fix the left click thing soon.

**Comment by shone-zmaj** [comment]
ok thx.

**Comment by megoesrawr** [comment]
Fixed this. Its on spigot now.
