### ISSUE TITLE
A piston with slime blocks can break protected signs and shulker boxes

### ISSUE THREAD

**Issue by iPyronic** [megoesrawr/LWCEntityLocking#22]
When slime blocks were added in MC 1.8, pistons became capable of moving blocks off to the side instead of always being directly in front of the piston. By using slime blocks, a piston can reach a shulker box or the block a sign is on and push it without facing it. Doing so will cause the shulker box or sign to drop to the ground as an item. The getLength() method in BlockPistonExtendEvent has been deprecated due to the change in piston behavior, being replaced with getBlocks(). Both BlockPistonExtendEvent and BlockPistonRetractEvent need to be updated to iterate over getBlocks() if they are to correctly cancel for affected protections.

Tested using a newly downloaded 1.8.0 plugin jar from spigotmc.org.

**Comment by megoesrawr** [comment]
Spigot doesn't support sticky pistons in the retract event. No idea why... but i fixed the extend part.

**Comment by iPyronic** [comment]
I'm not sure what you mean. It looks like the retract event handles sticky pistons just fine (tested using retractEvent.getBlocks().getSize()) D:

Also, the new extend event fix seems to only check a few locations near the piston instead of iterating over each block to check if it can move it. In the attached picture, all of the red and blue shulker boxes are protected. If either of the blue ones are there, it stops the piston from extending. If both blues are gone, the entire thing moves up and all red shulker boxes are destroyed even though they were locked.
![2017-04-30_11 11 34](https://cloud.githubusercontent.com/assets/5827887/25565906/f164bdf4-2d95-11e7-922f-389914067bc1.png)
Note: Obsidian is one of the materials that doesn't stick to slime blocks (it won't be listed in getBlocks() anyways).

For both events, I assume you could do something along the lines of this:
`for(Block block : event.getBlocks()){
   if(block is locked || block is holding a sign/door that is locked){
      event.setCancelled();
      return;
   }
}`

**Comment by megoesrawr** [comment]
It doesn't work like that.

This is the current slimeblock system:
		Block moved = piston.getRelative(direction);
		for (BlockFace bf : POSSIBLE_FACES) {
			Block slime = moved.getRelative(direction);
			Block sign = slime.getRelative(bf, 1);
			if ((lwc.findProtection(sign) != null)) {
				event.setCancelled(true);
				return;
			}
		}

**Comment by iPyronic** [comment]
That system assumes there's only 1 slime block though and that it's directly in front of the piston, right? But slime blocks can chain together like in the picture.

**Comment by megoesrawr** [comment]
This doesn't work either.

```
		for (Block meh : event.getBlocks()) {
			Protection protection = (lwc.findProtection(meh.getLocation()));

			// We don't want that!
			if (meh.getType() == Material.AIR) {
				break;
			}

			if (protection != null) {
				event.setCancelled(true);
				break;
			}
                  }
```

**Comment by iPyronic** [comment]
I'm not understanding your reasoning... After you said that, I tested the change myself and it seemed to work perfectly for wallSigns/shulkerBoxes. In the following image, I placed a private sign on the grass block, and then I powered off the piston to trigger a retract event.
![2017-04-30_15 46 22](https://cloud.githubusercontent.com/assets/5827887/25567843/37ed3668-2dbc-11e7-88e9-5e8592797ede.png)
These are the changes I made to the code (with the debug message still included):
(also, getBlocks() wont have any air in it, so there doesn't need to be a check for it)
```java
@EventHandler(ignoreCancelled = true)
public void onBlockPistonRetract(BlockPistonRetractEvent event) {
	if (!LWC.ENABLED) {
		return;
	}
	if(isPistonsLoadProtected(event.getBlocks())){
		event.setCancelled(true);
	}
}

@EventHandler(ignoreCancelled = true)
public void onBlockPistonExtend(BlockPistonExtendEvent event) {
	if (!LWC.ENABLED) {
		return;
	}
	if(isPistonsLoadProtected(event.getBlocks())){
		event.setCancelled(true);
	}
}

private boolean isPistonsLoadProtected(List<Block> blocks){
	LWC lwc = plugin.getLWC();
	for(Block block : blocks){
		Protection protection = lwc.findProtection(block);
		if(protection != null){
			Bukkit.broadcastMessage(ChatColor.DARK_RED+" Load is protected by: "+ChatColor.RED.toString()+block.getType());
			return true;
		}
	}
	return false;
}

**Comment by megoesrawr** [comment]
There fixed...
