### ISSUE TITLE
Breaking a block near certain wall signs removes sign protection

### ISSUE THREAD

**Issue by iPyronic** [megoesrawr/LWCEntityLocking#23]
If you place a sign on the southern or eastern side of a block (positive X or positive Z), and then break a block on the opposite side it's attached from, the sign will be unregistered. In the image below, breaking any of the clear glass has no effect, but breaking the red glass will remove the protection of the adjacent sign. Using /cinfo on the red glass shows that it has the sign's protection.
![2017-04-27_11 14 10](https://cloud.githubusercontent.com/assets/5827887/25493111/b4299ba6-2b3a-11e7-9f4f-ee52cf3f7b9f.png)

Tested using a newly downloaded 1.8.0 plugin jar from spigotmc.org.

**Comment by megoesrawr** [comment]
Cant reproduce..
![2017-04-29_13 45 03](https://cloud.githubusercontent.com/assets/7830406/25557559/1e8a9cae-2ce2-11e7-8675-0e75bd48c724.png)
![2017-04-29_13 45 18](https://cloud.githubusercontent.com/assets/7830406/25557561/2343eb92-2ce2-11e7-822e-53ba71905bfc.png)

**Comment by megoesrawr** [comment]
I fixed this. i will release it soon.
