### ISSUE TITLE
Pushing a block next to a chest using a piston

### ISSUE THREAD

**Issue by sigmaroot** [megoesrawr/LWCEntityLocking#25]
It is possible to push blocks with a piston next to protected chests.

**Reproduce:**
Protect a chest (another player), place a block 2 blocks away, place a piston and push the block towards an empty block next to the protected chest.

When using CraftBook and its pipes, it is possible to empty the whole chest when a piston is pushed by a second piston to the chest.

**Comment by Platinteufel** [comment]
Should be fixed on CraftBook side.

**Comment by sigmaroot** [comment]
What do you mean?
