### ISSUE TITLE
LWC error with locked itemframes

### ISSUE THREAD

**Issue by Castiella** [megoesrawr/LWCEntityLocking#29]
Hi there,

When we lock an item frame on a chest, then go to unlock it - it says "LWC: you have a pending action but another plugin canceled it"

You have to do /lwc admin remove ID  to remove the protection and then break the itemframe.

This only happens on chests. Do you know why this is being caused?

**Comment by TopicDogg** [comment]
Hello

I'm also having an issue with itemframes being unable to be locked or unlocked by non-op players. They'll just punch it off when trying to lock it, right-clicking doesn't work for some reason.
Unlocking just doesn't work at all.
OP's can lock them with either left or right click, same with unlocking.

Any solutions to this issue?

Thanks in advance!

**Comment by megoesrawr** [comment]
@TopicDogg add "lwc.lockentity." then the entity name in ALL CAPS or "lwc.lockentity.all" to lock the item frame.

@Castiella  I JUST tested it and cant seem to recreate it. Sorry. What version of Minecraft are you using?

**Comment by kobini2** [comment]
I do have the same issue.
There is no error, and it happens with:
 - item frames
 - paintings
It doesn't happen with:
- armor stands
