### ISSUE TITLE
issue with fake block

### ISSUE THREAD

**Issue by JokerLiuPro** [megoesrawr/LWCEntityLocking#32]
```
Paper version git-Paper-1182 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
GriefPrevention 16.7.1
LWC Unofficial - Entity locking 1.8.2
ProtocolLib v4.4.0-SHAPSHOT-b381

```
http://i.imgur.com/0N9mWWS.png
The imgur image show that after the chest become diamond_block (GriefPrevention's claim marker) and player can be access the LWC protected chest.
On the other hand, GriefPrevention's maintainer claim that it's just a fake block to the client and it shouldn't be any different to the server.

(update 11:44AM GMT+8)
it not only happen with GriefPrevention, all plugin which can changing block (Fake block)
also with ProdigyGadget 
"Paintballgun
Paint the wall, you can paint other player too !
I guarantee that this gadget does not destroy anything in your world."

**Comment by megoesrawr** [comment]
Fake blocks are handled in different ways. Tell the owners of the plugins to fix it. I cant.
