### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by TheRealB** [megoesrawr/LWCEntityLocking#33]
Most PreparedStatements in:
/src/com/griefcraft/sql/PhysDB.java

doesnt get closed correctly and creates huge amounts of open PreparedStatements.

Especially saveProtection which is called frequently, creates thousands of never unloaded PreparedStatements

**Comment by megoesrawr** [comment]
Uploading fix right now.

**Comment by ScuroK** [comment]
@megoesrawr 
Please see my issue #34
i think its related to this. since i downgraded to 1.8.2 the problem is gone
