### ISSUE TITLE
Errors on purge again.

### ISSUE THREAD

**Issue by ScuroK** [megoesrawr/LWCEntityLocking#35]
I get tons of error on /lwc admin purge
First i thought it was fixed but then the errors returned.

#34

**Comment by sigmaroot** [comment]
Confirmed. There is a new 1.8.9 build.
I'm gonna try it in a few minutes.

Seems that this error occurs if you perform a second pruge command since restart.

I'm gonna report the results of the new 1.8.9 dev build. here.

**Comment by sigmaroot** [comment]
Seems to be successfully fixed in 1.8.9 😄
