### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by sigmaroot** [megoesrawr/LWCEntityLocking#37]
Hello,

Using **/lwc admin cleanup** does nothing.

Version: 1.9.3

**Comment by sigmaroot** [comment]
Can this be verified?

**Comment by megoesrawr** [comment]
Seems to work for me.

**Comment by sigmaroot** [comment]
Ok, what server software are you using? CB? Spigot?

I'm going to test it again on a new server with only a few protections.

**Comment by megoesrawr** [comment]
Spigot and try to use the latest version.

**Comment by sigmaroot** [comment]
I have b1486 (1.12.2 spigot) and only EntityLWC and PermissionsEx enabled.

Running **/lwc admin cleanup** can be done, but it does not display, that it has finished.

When trying to stop the server, the following error occurs:

https://pastebin.com/c39TnNuT

And this one when using PaperSpigot: https://pastebin.com/1gD9kRq6

**Comment by sigmaroot** [comment]
Oh wait, there is a 1.9.4? I'm testing with that version...

**Comment by sigmaroot** [comment]
Ok, I think I found the issue. It has nothing to do with 1.9.3 or 1.9.4. It is a generally bug.

It seems that a deadlock is triggered if you try to run **/lwc admin cleanup** BEFORE any database connection is established by using a protection or something.

Example: Start server, join and enter command. It hangs and does nothing. Open a protected chest -> The cleanup is started and the following error is shown in the console (PaperSpigot): https://pastebin.com/8x7ibcvi

Example to avoid deadlock: Start server, open a protected chest, close the chest, run command. Everything is fine.

**Comment by sigmaroot** [comment]
It crashed my server running a cleanup:

https://pastebin.com/7iwqJPpD
