### ISSUE TITLE
[1.6.2] /cremoveall, /climits and /lwc admin purge not working

### ISSUE THREAD

**Issue by sigmaroot** [megoesrawr/LWCEntityLocking#4]
I figured out, that the command /cremoveall (and also /lwc admin purge [player]) are not working correctly. It's displaying "Removed all protections sucessfully" but they still exist in the database.
I tried it also with an older version (1.6.1) and it's working correctly there.

Version: 1.6.2
Database-Type: MySQL-Server (both tests)

Can you just check this out?
Thanks!

Edit: Tried again with 1.6.2 after removing all protections with 1.6.1 and it worked. Maybe some problemes because of old data in the database? Seems like an problem caused by UUID... /climits says: 0 - But there are still signs, using /cinfo telling me "Protection: Private"...

Edit: Yep, seems that it's caused by UUID. New signs that I create have "Name: [name] [uuid]" and they are removed with /cremoveall. But my old signs (older than 1 year) are still protected by "Name: [name]".

**Comment by megoesrawr** [comment]
I cant remove UUID and I've been REALLY busy with Jobs and stuff...
