### ISSUE TITLE
EntityLWC connected to MySQL database causes intense lag from piston retract events

### ISSUE THREAD

**Issue by aeonlamb** [megoesrawr/LWCEntityLocking#40]
I'm not sure when this started happening, but I started noticing it after updating my server to 1.12.2: Piston retract events, especially pistons that retract quickly/often, cause IMMENSE lag. I narrowed it down to EntityLWC that was causing this issue, based upon my timings reports. I'm using EntityLWC version 1.9.3, although I tried a few older versions as well and none of them fixed this problem. 

To test this process, I created a setup that would fire off 60 pistons every other tick. The pistons were not nearby any existing LWC protections. The test dropped my server's TPS from a solid ~20.0 down to ~3.5 TPS. [Here's my timings report from that test](https://timings.aikar.co/?id=3c049a6c973c46d4bb56dd820b7afc5b). I tried this same on a test server with all the same plugins installed (including EntityLWC), and the TPS remained a constant ~20.0 for the whole test. The only discernible difference between these two tests was that on my test server LWC was not connected to a MySQL database. 

What I want to know is, what is the reason the database is being queried every time a piston retracts? At the moment, anyone with a decent amount of redstone could absolutely nuke my server's performance, and even just having a good amount of people online loading chunks with redstone mechanisms in it drops my server's TPS a lot further than it should.

**Comment by megoesrawr** [comment]
I have tested this a bit and I don't seem to get the same lag so i don't know whats going on.

**Comment by aeonlamb** [comment]
I'm using the updated version, entityLWC 1.9.4 now, and it doesn't seem to have fixed this issue... I took a more prolonged test this time, leaving the piston contraption on for ~5 minutes. In the timings report [here](https://timings.aikar.co/?id=3ac8f7ec23f3497e976802500a221562) you can narrow down the timings to include basically just the testing period alone. The lag is almost entirely due to LWC. I actually did this test with a few other players on so there might be some irrelevant stuff showing up there, but you get the picture. Same as before, I'm using LWC with a MySQL database connected, testing this on a live server (can't really be bothered to try figuring out how to setup MySQL right now). 

[Here's my config](https://ghostbin.com/paste/j8q6d), as well as [plugins list](https://i.imgur.com/q4hsu2d.png) if it helps. Only other plugin using the database is Coreprotect, which definitely doesn't cause lag like this. I'm also running Paper 1.12.2 , build 1282. If the source of this lag can't be helped, any sort of advice on reducing the lag would be cool too (although perhaps I should be asking that in a help thread ...)

Either way, thanks for looking into the issue and keeping this plugin alive!

**Comment by DoreK333** [comment]
https://timings.aikar.co/?id=dedabd58b20f457e8dd8f29773ec2ede
PaperSpigot 1327 (1.12.2)
The symptoms are very similar, I have ZHorse, LWC and LogBlock plugins connected to the database server (MariaDB), but the delay causes LWC.
TPS drops are very large, up to 11 with 3 people online. I hope that we will solve this problem! :)

**Comment by megoesrawr** [comment]
It might be paper spigot, i used normal spigot and didn't have this issue.

**Comment by aeonlamb** [comment]
Why closed? I don't think Paper is causing the issue itself... unless I can see some proof of that. I'm not an expert or anything but many server owners use Paper, it's worth at least looking into

**Comment by megoesrawr** [comment]
Sorry missclick.

**Comment by megoesrawr** [comment]
![2018-02-17_18 02 23](https://user-images.githubusercontent.com/7830406/36346450-c266eb36-140c-11e8-9128-4cabe4bb790b.png)
I tried this many pistons on paperspigot 1.12.2 newest version and i only dropped to 19.97 tps.

https://timings.aikar.co/?id=9af09ad9fcab4b3aa9d787a7e67af763 Timings after 5 mins.

**Comment by aeonlamb** [comment]
Sorry it took a few days to respond, didn't have time to update the server to check, but you're right- the lag is gone on latest Paper. Guess it was an issue on their end. Sorry for the trouble!

**Comment by aeonlamb** [comment]
Hold on, I feel stupid right now. Turns out LWC was actually disabled because of the SQL server being offline. Now I'm getting spammed with errors out the wazoo from LWC about not being able to establish a SQL connection, even though other plugins can access it... that's not relevant to this issue of course, though. Basically, ignore my last comment, the test was invalid. 

As soon as I can get this figured out I'll try testing again.

**Comment by aeonlamb** [comment]
Managed to get Mysql under control again. Tested again with the same piston setup, latest version of Paper, it still happens. TPS tanks from BlockPistonRetractEvent. 

I'm just switching back to sqlite storage because it's overall better for my server...

**Comment by megoesrawr** [comment]
Ok.

**Comment by Tiippex** [comment]
So is sqlite or mysql storage better with LWC?

**Comment by megoesrawr** [comment]
sqlite for now

**Comment by Tiippex** [comment]
okay thanks
