### ISSUE TITLE
ARMOR_STAND cannot be unlocked

### ISSUE THREAD

**Issue by sigmaroot** [megoesrawr/LWCEntityLocking#42]
Hello 😃 

Running version 1.9.4, an ARMOR_STAND can be locked by /cprivate or by autoregister. But the usage of /cremove is not working as expected.

You may have a look into this, thanks 👍

**Comment by megoesrawr** [comment]
Will be fixed in 2.0.0

**Comment by sigmaroot** [comment]
Thanks!
