### ISSUE TITLE
Error (probably for sql)

### ISSUE THREAD

**Issue by DoreK333** [megoesrawr/LWCEntityLocking#44]
When opening the furnace I received an error, but it was a one-off situation and I have no idea why it happened.
https://hastebin.com/ahepexofoj.md
https://imgur.com/a/9wZ9S
Timings: https://timings.aikar.co/?id=c0d5a930f5e74d518dc1b5cc68e4db5d

**Comment by megoesrawr** [comment]
I will fix this in 2.0.0
