### ISSUE TITLE
2.0 database upgrade not quite workin...

### ISSUE THREAD

**Issue by mrcoffee1026** [megoesrawr/LWCEntityLocking#47]
I'm not sure how much value the backup will be since it would have needed to be converted to be used... but I'd say about 70% of the locks were lost in the transition... every time I unlock a sign it says "successfully unlocked Entity HORSE"... so maybe the conversion script needs a bit of work yet?

**Comment by megoesrawr** [comment]
Its will  a work in progress but I'm trying to get it out for when 1.13 comes out.

**Comment by mrcoffee1026** [comment]
Ok well... what it didn't state in the really important info was that... this won't work with 1.12.2 which... from how everything kind of fell apart when I started using it, it should probably also state.  It's been misidentifying pretty much everything... which I thought would just go away when I had a 1.13 to install but... because it's misidentifying things or.... something... it also starts randomly saying "removing corrupt protection" to things that have not been changed in a any way... unlocking things left and right, I've had to replace dozens of chests to try to keep up with it for a little bit thinking maybe... the newer code would remedy but then... the new stuff just unlocks itself later too so... anyway I'm hoping this is a "because I don't have 1.13" thing and not a "this upgrade doesn't work at all" thing.  In any case along with the "this makes it compatible with 1.13, you should probably add "this makes it incompatible with 1.12.2". so that people don't make the same mistake.  I did have a backup of the db so I rolled back, though doing so lost about a week of stuff it's the lesser of evils right now.

**Comment by mrcoffee1026** [comment]
Still a disaster.  Most items that were locked are now no longer registered as being anyone's.  It seems to be at least not calling items the wrong thing now, but that's the only improvement, everything else that was a problem with your previous release is still a problem:  nearly all locks need to be remade.  When I right click an item that is registered, it no longer says what item it is... I don't know if this part of the issue or part of the update for the 1.13 item ids.  I've tried restoring the database from its original a few times with this version, different items are lost each time.  There's nothing in the logs about errors or anything in regards to why 95% of everything has been unlocked/deregistered.  Basically every chest/door/furnace/hopper setup would need to be replaced if I were to put this on my live server.  Again, should be noted in this version that is completely and irreparably incompatible with Minecraft 1.12.2 until you work out a solution.

**Comment by mrcoffee1026** [comment]
Still does not work as of the latest 2.0.5  Seems all chests have been unregistered, a few signs remain locked as they should be.
