### ISSUE TITLE
Armor stand dupe

### ISSUE THREAD

**Issue by PsychoLynx** [megoesrawr/LWCEntityLocking#5]
Using 7.2.2016 version of Spigot 1.8.8 and latest Entity LWC (No other plugins).
Placing an (autoprotected) armor stand and THEN rapidly breaking it causes two armor stands to drop instead of one.

**Comment by megoesrawr** [comment]
Sorry, I cant seem to get this to work. Ima close it for now, if I see it happen, I'll reopen.

**Comment by PsychoLynx** [comment]
Sent a video via PM
