### ISSUE TITLE
Error while first run 2.0.1

### ISSUE THREAD

**Issue by Superdarco** [megoesrawr/LWCEntityLocking#57]
Hi, I do not know if this helps you, I discovered that when the plugin was first started, version 2.0.1 came out this error, spigot 1.11.2:

https://pastebin.com/EPFYWW3k

But when I put the database of version 1.9.4 that is fixed because it already goes like this:

[15:28:09] [Server thread/INFO]: [LWC] Enabling LWC v2.0.1
[15:28:09] [Server thread/INFO]: [LWC] Connecting to SQLite
[15:28:10] [Server thread/INFO]: [LWC] Updating to 1.13 material name system.

I hope this helps you for something, and thanks for keeping this plugin active, Regards

**Comment by megoesrawr** [comment]
Fixing in 2.0.2

**Comment by Superdarco** [comment]
Well, it seems that is already working well, if something else comes out, I'll let you know, Regards
