### ISSUE TITLE
I can not add a player

### ISSUE THREAD

**Issue by DoreK333** [megoesrawr/LWCEntityLocking#62]
After entering the "/cmodify nick" command and hitting the chest with your hand, a message appears that the player has been granted permission, although this is not the case. The player did not get permission to lock, he is also not on the list in the "/cinfo" command.
Timings: https://timings.aikar.co/?id=0f6fc416212e44b993f2022755f634de
/edit: The problem does not concern all protection.
/edit2: The same player also has a problem with the removal of protection. It appears to him that the protection has been removed, but the protection is still there. I also can not remove his protection.

**Comment by megoesrawr** [comment]
Try the newest one please.
