### ISSUE TITLE
Versions 2.0.1 and 2.0.2 do not write to preexisting database.

### ISSUE THREAD

**Issue by FatherWh0** [megoesrawr/LWCEntityLocking#72]
After updating 2.0.0 to 2.0.1 changes to chests are not written to the database file. This causes all changes to be lost during a restart. The same happens with 2.0.2. Returning to version 2.0.0 causes plugin to behave normally again, writing changes to it's database.

EntityLWC: 2.0.0, 2.0.1 & 2.0.2
paper 1.12.2 #1391

**Comment by theyapps** [comment]
Added a pull request that fixes this issue.

**Comment by khlfkk** [comment]
i got same issue and a newly created double chest protection which then has a /cremove applied will not actually remove the protection at all. It is very big issue, hope can fix it soon.

**Comment by theyapps** [comment]
@khlfkk That is a seperate issue #65

**Comment by megoesrawr** [comment]
Try the newest version now.

**Comment by Tsuser1** [comment]
The latest build is **confirmed to be working**.

**Comment by FatherWh0** [comment]
I can verify the database is being written to. I'll verify tomorrow that the LWC changes persist a restart as I restart once each night.

**Comment by FatherWh0** [comment]
This issue appears to be fixed. Thank you for your time and help.
