### ISSUE TITLE
[Request] Force Owner

### ISSUE THREAD

**Issue by cococow123** [megoesrawr/LWCEntityLocking#8]
Can you add a feature so if you transferred from old LWC (UUID's not supported) and when a player changes their name, it will update or something?

I was thinking of a command like "/lwc admin oldnameforceowner <player>" or something to get the player's UUID and get all protection owners UUID to transfer the block/entity.

Thanks,
Coco

(Message me on skype if you are confused)

**Comment by megoesrawr** [comment]
No, because of armor stands being in the code and forcing it to use 1.8 or higher spigot.
